CREATE TABLE IF NOT EXISTS GAME_USERS (
  ID BIGINT AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  SALT VARCHAR(44) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  BEST_RESULT INT DEFAULT NULL,
  LAST_RESULT INT DEFAULT NULL,
  AUTORITY INT DEFAULT 0
);

ALTER TABLE GAME_USERS ADD CONSTRAINT IF NOT EXISTS game_users_pk PRIMARY KEY (ID);

ALTER TABLE GAME_USERS ADD CONSTRAINT IF NOT EXISTS game_users_unique_names UNIQUE (NAME);