CREATE TABLE IF NOT EXISTS GAME_USERS (
  ID BIGINT AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  SALT VARCHAR(44) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  BEST_RESULT INT DEFAULT NULL,
  LAST_RESULT INT DEFAULT NULL,
  AVERAGE_RESULT DECIMAL DEFAULT NULL,
  AUTHORITY INT DEFAULT 0
);

ALTER TABLE GAME_USERS ADD CONSTRAINT IF NOT EXISTS game_users_pk PRIMARY KEY (ID);

ALTER TABLE GAME_USERS ADD CONSTRAINT IF NOT EXISTS game_users_unique_names UNIQUE (NAME);

MERGE INTO GAME_USERS (NAME, SALT, PASSWORD, BEST_RESULT, LAST_RESULT, AVERAGE_RESULT, AUTHORITY) KEY (NAME)
VALUES ('Владимир П.', '1', '1', 1, 1, 1, 86);

MERGE INTO GAME_USERS (NAME, SALT, PASSWORD, BEST_RESULT, LAST_RESULT, AVERAGE_RESULT, AUTHORITY) KEY (NAME)
VALUES ('RAMZAN', '3', '3', 3, 148, 3, 10);

MERGE INTO GAME_USERS (NAME, SALT, PASSWORD, BEST_RESULT, LAST_RESULT, AVERAGE_RESULT, AUTHORITY) KEY (NAME)
VALUES ('Albert E.', '6', '6', 6, 6, 7.5, 0);

MERGE INTO GAME_USERS (NAME, SALT, PASSWORD, BEST_RESULT, LAST_RESULT, AVERAGE_RESULT, AUTHORITY) KEY (NAME)
VALUES ('Воронин Лёня', '46', '46', 24, 35, 46.21, 0);